<img src="datamecum_logo.png" align="right" style="float" width="400">
<font color="#CA3532"><h1 align="left">Programa técnico intensivo en data science. Datamecum.</h1></font>
<font color="#6E6E6E"><h2 align="left">Módulo Introducción a Matematicas</h2></font> 
<font color="#6E6E6E"><h2 align="left">Tarea 1.</h2></font> 

#### Juan Gómez-Sanchis
##### Alumna: Maria Balos

TO DO: *
* Ejercicio 1. Crea un notebook nuevo de jupyter denominado Tarea1.ipynb y haz lo necesario para crear un array formado por un vector fila [10,12,14,16]
* Ejercicio 2. Determina el tipo de datos que contiene el array que has creado en el ejercicio anterior.
* Ejercicio 3. Determina el tamaño del array anterior utilizando un método de python. 
* Ejercicio 4. Crea dos matrices de tamaño 5x4 que contengan ceros y unos respectivamente.
* Ejercicio 5. Crea un array que contenga una matriz identidad 7x7
* Ejercicio 6. Crea un array unidimensional que contenga en cada posición los números del 1 al 100.
* Ejercicio 7. Crea un array 3x3 con los 9 primeros números enteros pares empezando en 2 y suma 1 a los elementos de la diagonal de dicho array.
* Ejercicio 8. Calcula la inversa (1/elemento) de cada elemento del array resultado del ejercicio anterior.
* Ejercicio 9. Calcula la raiz cuadrada de los elementos del array resultado del ejercicio anterior.*

In [2]:
import numpy as np

Ejercicio 1. Crea un notebook nuevo de jupyter denominado Tarea1.ipynb y haz lo necesario para crear un array formado por un vector fila [10,12,14,16]

In [8]:
list = [10,12,14,16]
my_array = np.array(list)
my_array

array([10, 12, 14, 16])


Ejercicio 2. Determina el tipo de datos que contiene el array que has creado en el ejercicio anterior.


In [10]:
my_array.dtype

dtype('int64')

Ejercicio 3. Determina el tamaño del array anterior utilizando un método de python. 

In [11]:
my_array.shape

(4,)

Ejercicio 4. Crea dos matrices de tamaño 5x4 que contengan ceros y unos respectivamente.

In [12]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Ejercicio 5. Crea un array que contenga una matriz identidad 7x7


In [14]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

 Ejercicio 6. Crea un array unidimensional que contenga en cada posición los números del 1 al 100.

In [17]:
np.arange(1, 101)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

Ejercicio 7. Crea un array 3x3 con los 9 primeros números enteros pares empezando en 2 y suma 1 a los elementos de la diagonal de dicho array.


In [35]:
my_2_list = [[2,4,6],[8,10,12],[14,16,18]]
array_enteros = np.array(my_2_list)

array_enteros += np.eye(3, dtype= np.int32)
array_enteros

array([[ 3,  4,  6],
       [ 8, 11, 12],
       [14, 16, 19]])

Ejercicio 8. Calcula la inversa (1/elemento) de cada elemento del array resultado del ejercicio anterior.

In [36]:
1/ array_enteros

array([[0.33333333, 0.25      , 0.16666667],
       [0.125     , 0.09090909, 0.08333333],
       [0.07142857, 0.0625    , 0.05263158]])

Ejercicio 9. Calcula la raiz cuadrada de los elementos del array resultado del ejercicio anterior.*

In [37]:
array_enteros ** 2

array([[  9,  16,  36],
       [ 64, 121, 144],
       [196, 256, 361]])