<img src="datamecum_logo.png" align="right" style="float" width="400">
<font color="#CA3532"><h1 align="left">Programa técnico intensivo en data science. Datamecum.</h1></font>
<font color="#6E6E6E"><h2 align="left">Módulo Introducción a Matematicas</h2></font> 
<font color="#6E6E6E"><h2 align="left">Tarea 2.</h2></font> 

#### Juan Gómez-Sanchis
##### Alumna: Maria Balos

TO DO: *
* Ejercicio 1. Crea un notebook de jupyter denominado Tarea11.ipynb y a continuación crea un vector fila que contenga los numeros enteros del 20 al 30.
* Ejercicio 2. Crea otro array seleccionando los 6 primeros elementos del array que has creado en el ejercicio anterior. 
* Ejercicio 3. Crea un vector fila llamado Ejer3a con los números enteros del 100 al 200. Cuando lo hayas hecho crea un nuevo vector denominado Ejer3b que contenga las 10 primeras posiciones de Ejer3a.
* Ejercicio 4. En el array resultado del ejercicio 3 (Ejer3b) haz que en las posiciones pares el valor sea 9999. Comprueba el valor del array Ejer3a. Cómo explicas el resultado al visualizar Ejer3a?. Cómo lo resolverías?
* Ejercicio 5. Crea un array 3x3 denominado Ejer5a que contenga los números enteros del 9 al 1 dispuestos en filas. Crea un un array denominado Ejer5b que contenga las 2 primeras filas de Ejer5a. Crea un un array denominado Ejer5c que contenga las 2 primeras columnas de Ejer5a. Crea un un array denominado Ejer5c que contenga la submatriz 2x2 de la parte inferior izquierda de Ejer5a.

In [9]:
import numpy as np

* Ejercicio 1. Crea un notebook de jupyter denominado Tarea11.ipynb y a continuación crea un vector fila que contenga los numeros enteros del 20 al 30.

In [8]:
def generate_pair_numbers(range_list: list) -> list:
    """A piece of code that returns the pairs for a range of numbers.

    Args:
        range_list (list): A list with the range being the first element the start and the second one the end.

    Returns:
        list: The list with the pair elements.
    """
    numbers = []
    for number in range (range_list[0], range_list[1]):
        if number %2==0:
            numbers.append(number)
    return numbers

my_list = generate_pair_numbers([20,30])
my_list

[20, 22, 24, 26, 28]

* Ejercicio 2. Crea otro array seleccionando los 6 primeros elementos del array que has creado en el ejercicio anterior. 

In [11]:
np.array(my_list[:3])

array([20, 22, 24])

* Ejercicio 3. Crea un vector fila llamado Ejer3a con los números enteros del 100 al 200. Cuando lo hayas hecho crea un nuevo vector denominado Ejer3b que contenga las 10 primeras posiciones de Ejer3a.

In [18]:
ejer3a = np.arange(100,201)
ejer3a

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151,
       152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164,
       165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177,
       178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190,
       191, 192, 193, 194, 195, 196, 197, 198, 199, 200])

In [19]:
ejer3b = ejer3a[:10]
ejer3b

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

* Ejercicio 4. En el array resultado del ejercicio 3 (Ejer3b) haz que en las posiciones pares el valor sea 9999. Comprueba el valor del array Ejer3a. Cómo explicas el resultado al visualizar Ejer3a?. Cómo lo resolverías?

In [70]:
def sustitute_pair_elements(array_elem, new_number: int) -> None:
    """A code block that takes an array element and add a given number to the positions where the elements are pairs.

    Args:
        array_elem (_type_): The array to be modified.
        new_number (int): The number whith which it would be substituted the original one.
    """
    for element in array_elem:
        if element % 2 == 0:
            positions = np.where (array_elem == element)
            for position in positions:
                array_elem[position] = new_number
ejer3b

array([9999,  101, 9999,  103, 9999,  105, 9999,  107, 9999,  109])

* Ejercicio 5. Crea un array 3x3 denominado Ejer5a que contenga los números enteros del 9 al 1 dispuestos en filas. Crea un array denominado Ejer5b que contenga las 2 primeras filas de Ejer5a. Crea un un array denominado Ejer5c que contenga las 2 primeras columnas de Ejer5a. Crea un un array denominado Ejer5d que contenga la submatriz 2x2 de la parte inferior izquierda de Ejer5a.

In [61]:
#create a 3x3 array with the real elements from 9 to 1.
ejer5a = [[9,8,7],[6,5,4],[3,2,1]]
ejer5a = np.array(ejer5a)
ejer5a

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [65]:
#Create the variable ejer5b with the first row of ejer5a.
ejer5b = ejer5a[:2, :]
ejer5b

array([[9, 8, 7],
       [6, 5, 4]])

In [66]:
#Create the variable ejer5c with the first 2 col of ejer5a.
ejer5c = ejer5a[:, :2]
ejer5c

array([[9, 8],
       [6, 5],
       [3, 2]])

In [69]:
#Create the variable ejer5d with the first 2x2 submatriz of the bottom left side of ejer5a.
ejer5d = ejer5a[1:, :2]
ejer5d

array([[6, 5],
       [3, 2]])