<img src="datamecum_logo.png" align="right" style="float" width="400">
<font color="#CA3532"><h1 align="left">Programa técnico intensivo en data science. Datamecum.</h1></font>
<font color="#6E6E6E"><h2 align="left">Módulo Introducción a Matematicas</h2></font> 
<font color="#6E6E6E"><h2 align="left">Tarea 3.</h2></font> 

#### Juan Gómez-Sanchis
##### Alumna: Maria Balos

TO DO: 
* Ejercicio 1. Crea un notebook de jupyter denominado Tarea12.ipynb y a continuación crea un matriz denominada Ejer1 de 20 elementos del 0 al 20 y organizados en una matriz 2x10 
* Ejercicio 2. Crea una matriz denominada Ejer2 de tamaño 2x10 compuesta por elementos iguales 10. Realiza la operación matricial Ejer1·T(Ejer2).
* Ejercicio 3. Crea un tensor de orden de orden 3 denominado Ejer3 de tamaño 10x9x5 compuesto por elementos del 1 al 450 dispuestos en el tensor por filas dentro de la cada matriz del tensor.
* Ejercicio 4.Vamos a jugar con el array Ejer3, y a comprobar lo que recuerdas de indexar arrays...
  * Extrae la primera matriz 9x5 del tensor y denominalo Ejer4a
  * Extrae la última matriz 9x5 del tensor y denominalo Ejer4b
  * Realiza la operación matricial Ejer4a·T(Ejer4b)
  * Extrae un vector denominado Ejer4c constituido por la segunda fila de la segunda matriz del tensor Ejer3.
  * Extrae un vector denominado Ejer4d constituido por la primera fila de la tercera matriz del tensor Ejer3.
  * Cuál es el valor del producto escalar de los vectores Ejer4c y Ejer4d?.
  * Crea un vector columna denominado Ejer4e compuesto por lo elementos de la última columna de la primera matriz de Ejer3.
  * Crea un vector columna denominado Ejer4f compuesto por los elementos de tercera columna de la cuarta matriz de Ejer3.
  * Cuál es el valor del producto escalar de los vectores Ejer4e y Ejer4f?. Utiliza la función np.dot para conseguirlo

In [4]:
import numpy as np

Ejercicio 1. Crea un notebook de jupyter denominado Tarea12.ipynb y a continuación crea un matriz denominada Ejer1 de 20 elementos del 0 al 20 y organizados en una matriz 2x10 

In [5]:
ejer1 = np.arange(20).reshape(2,10)
ejer1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

Ejercicio 2. Crea una matriz denominada Ejer2 de tamaño 2x10 compuesta por elementos iguales 10.

In [6]:
ejer2 = np.full((2, 10), 10)
ejer2

array([[10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10]])

Realiza la operación matricial Ejer1·T(Ejer2).

In [22]:
#No es posible realizar la operacion  ya que las dos matrices no didponen de la misma forma.
np.dot(ejer1, ejer2.T)

array([[ 450,  450],
       [1450, 1450]])

* Ejercicio 3. Crea un tensor de orden 3 denominado Ejer3 de tamaño 10x9x5 compuesto por elementos del 1 al 450 dispuestos en el tensor por filas dentro de la cada matriz del tensor.

In [23]:
ejer3 = np.arange(450).reshape(10,9,5)
ejer3

array([[[  0,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14],
        [ 15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24],
        [ 25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34],
        [ 35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44]],

       [[ 45,  46,  47,  48,  49],
        [ 50,  51,  52,  53,  54],
        [ 55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64],
        [ 65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74],
        [ 75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84],
        [ 85,  86,  87,  88,  89]],

       [[ 90,  91,  92,  93,  94],
        [ 95,  96,  97,  98,  99],
        [100, 101, 102, 103, 104],
        [105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114],
        [115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124],
        [125, 126, 127, 128, 129],
        [130, 131, 132, 133, 134]],

       [[135, 136, 137, 138, 139],
        [140, 

Ejercicio 4. Vamos a jugar con el array Ejer3, y a comprobar lo que recuerdas de indexar arrays...
  * Extrae la primera matriz 9x5 del tensor y denominalo Ejer4a

In [24]:
ejer4a = ejer3[0]
ejer4a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44]])

* Extrae la última matriz 9x5 del tensor y denominalo Ejer4b

In [25]:
ejer4b = ejer3[-1]
ejer4b

array([[405, 406, 407, 408, 409],
       [410, 411, 412, 413, 414],
       [415, 416, 417, 418, 419],
       [420, 421, 422, 423, 424],
       [425, 426, 427, 428, 429],
       [430, 431, 432, 433, 434],
       [435, 436, 437, 438, 439],
       [440, 441, 442, 443, 444],
       [445, 446, 447, 448, 449]])

 * Realiza la operación matricial Ejer4a·T(Ejer4b)

In [21]:
#No se puede ya que las formas de los arrays no son las mismas.
np.dot(ejer4a, ejer4b.T)

array([[ 4080,  4130,  4180,  4230,  4280,  4330,  4380,  4430,  4480],
       [14255, 14430, 14605, 14780, 14955, 15130, 15305, 15480, 15655],
       [24430, 24730, 25030, 25330, 25630, 25930, 26230, 26530, 26830],
       [34605, 35030, 35455, 35880, 36305, 36730, 37155, 37580, 38005],
       [44780, 45330, 45880, 46430, 46980, 47530, 48080, 48630, 49180],
       [54955, 55630, 56305, 56980, 57655, 58330, 59005, 59680, 60355],
       [65130, 65930, 66730, 67530, 68330, 69130, 69930, 70730, 71530],
       [75305, 76230, 77155, 78080, 79005, 79930, 80855, 81780, 82705],
       [85480, 86530, 87580, 88630, 89680, 90730, 91780, 92830, 93880]])

 * Extrae un vector denominado Ejer4c constituido por la segunda fila de la segunda matriz del tensor Ejer3.

In [ ]:
ejer4c = ejer3[1,1]
ejer4c

array([50, 51, 52, 53, 54])

 * Extrae un vector denominado Ejer4d constituido por la primera fila de la tercera matriz del tensor Ejer3.

In [ ]:
ejer4d = ejer3[2,0]
ejer4d

array([90, 91, 92, 93, 94])

 * Cuál es el valor del producto escalar de los vectores Ejer4c y Ejer4d?.

In [ ]:
np.dot(ejer4c,ejer4d)

23930

* Crea un vector columna denominado Ejer4e compuesto por lo elementos de la última columna de la primera matriz de Ejer3.

In [ ]:
ejer4e = ejer3[0, :, 4:]
ejer4e.shape

(9, 1)

 * Crea un vector columna denominado Ejer4f compuesto por los elementos de tercera columna de la cuarta matriz de Ejer3.

In [ ]:
ejer4f = ejer3[3, :, 3:4]
ejer4f.shape

(9, 1)

 * Cuál es el valor del producto escalar de los vectores Ejer4e y Ejer4f?. Utiliza la función np.dot para conseguirlo

In [ ]:
ejer4f.shape
ejer4e.shape
np.dot(ejer4f.T,ejer4e)

array([[35628]])